dist: xenial

addons:
  snaps:
  - name: hugo
    channel: extended

# Clean and don't fail
install:
  - rm -rf public || exit 0
# Build the website
script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
  fqdn: eta-chalmers.tk
